sudo: required
dist: trusty
language: generic

compiler:
- gcc

install:
  - sudo apt-get install -y cmake
  - sudo apt-get install -y software-properties-common
  - sudo apt-get install -y python-software-properties
  - echo "\n" | sudo add-apt-repository ppa:webupd8team/java
  - sudo apt-get update
  - echo debconf shared/accepted-oracle-license-v1-1 select true | \sudo debconf-set-selections
  - echo debconf shared/accepted-oracle-license-v1-1 seen true | \sudo debconf-set-selections
  - sudo apt-get install -y oracle-java8-installer
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp libg* /usr/lib/
  - sudo apt-get install -y cmake libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev
  - sudo apt-get install -y unzip
  - cd ~/
  - wget https://services.gradle.org/distributions/gradle-3.4-bin.zip
  - sudo unzip -d /opt/gradle gradle-3.4-bin.zip
  - export PATH=$PATH:/opt/gradle/gradle-3.4/bin
  - rm gradle-3.4-bin.zip
  - git clone --recursive https://github.com/eProsima/Fast-RTPS
  - cd Fast-RTPS
  - echo "export FASTRTPSHOME=${PWD}" >> ~/.bashrc 
  - echo "export PATH=$PATH:${PWD}/fastrtpsgen/scripts" >> ~/.bashrc 
  - export FASTRTPSHOME=${PWD} 
  - export PATH=$PATH:${PWD}/fastrtpsgen/scripts 
  - mkdir build -p && cd build
  - cmake ../ -DEPROSIMA_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install
  - make
  - make install
  - cd ../fastrtpsgen
  - gradle build

script:
  - cd
  - git clone https://github.com/ajimal1992/fastrtps_minimal.git
  - cd fastrtps_minimal
  - sudo ./compile.sh
